inv-menu:
  title: '&8Warp Menu'
  default-item: 'OAK_PLANKS'

messages:
  pluginPrefix: '&f[&b&lPW&f]'
  responseNoWarpsExist: '&e&l(!) &eNo warps currently exist.'
  responseWarpDoesNotExist: '&e&l(!) &eNo warp named &b&o<warp> &eexists.'
  responseWarpCreated: 'Warp &b&o<warp> &fhas been created!'
  responseWarpAlreadyExists: '&e&l(!) &eThe warp &b&o<warp> &ealready exists.'
  responseWarpRemoved: 'Warp &b&o<warp> &fhas been removed.'
  responseWarpRenamed: 'The display name of warp &b&o<warp> &fis now &b&o<name>&f.'
  responseWarpInvalidName: '&e&l(!) That is an invalid warp name.'
  responseItemUpdated: 'Item updated.'
  responseInvalidPerms: '&e&l(!) &eYou do not have permission to do that.'
  responseInvalidCmd: '&e&l(!) &eInvalid command, type &b&o/warp help &efor help. Perhaps you mistyped something?'
  responseLoreAdded: '&fLore &5<lore>&f &fadded to warp &b&o<warp>&f.'
  responseLoreSet: '&fLore &5<lore> &fset to line &b&o<line> &ffor warp &b&o<warp>&f.'
  responseLoreRemoved: '&fLore line &b&o<line> &ffor warp &b&o<warp> &fhas been removed.'
  responseLoreRemovedAll: '&fLore for warp &b&o<warp> &fhas been reset.'
  responseLoreDoesNotExist: '&e&l(!) &eThere is no line &b&o<line> &eof lore for warp &b&o<warp>&e.'