inv-menu:
  title: '&8Warp Menu'
  default-item: 'OAK_PLANKS'

messages:
  responseNoWarpsExist: '&f[&b&lPW&f] &e&l(!) &eNo warps currently exist.'
  responseWarpDoesNotExist: '&f[&b&lPW&f] &e&l(!) &eNo warp named &b&o<warp> &eexists.'
  responseWarpCreated: '&f[&b&lPW&f] Warp &b&o<warp> &fhas been created!'
  responseWarpAlreadyExists: '&f[&b&lPW&f] &e&l(!) &eThe warp &b&o<warp> &ealready exists.'
  responseWarpRemoved: '&f[&b&lPW&f] Warp &b&o<warp> &fhas been removed.'
  responseWarpRenamed: '&f[&b&lPW&f] The display name of warp &b&o<warp> &fis now &b&o<name>&f.'
  responseWarpInvalidName: '&f[&b&lPW&f] &e&l(!) That is an invalid warp name.'
  responseItemUpdated: '&f[&b&lPW&f] Item updated.'
  responseInvalidPerms: '&f[&b&lPW&f] &e&l(!) &eYou do not have permission to do that.'
  responseInvalidCmd: '&f[&b&lPW&f] &e&l(!) &eInvalid command, type &b&o/warp help &efor help. Perhaps you mistyped something?'
  responseLoreAdded: '&f[&b&lPW&f] &fLore &5<lore>&f &fadded to warp &b&o<warp>&f.'
  responseLoreSet: '&f[&b&lPW&f] &fLore &5<lore> &fset to line &b&o<line> &ffor warp &b&o<warp>&f.'
  responseLoreRemoved: '&f[&b&lPW&f] &fLore line &b&o<line> &ffor warp &b&o<warp> &fhas been removed.'
  responseLoreRemovedAll: '&f[&b&lPW&f] &fLore for warp &b&o<warp> &fhas been reset.'
  responseLoreDoesNotExist: '&f[&b&lPW&f] &e&l(!) &eThere is no line &b&o<line> &eof lore for warp &b&o<warp>&e.'